// Generated by generate-site-config.py — do not edit
window.PLANNING_SITE = {
  "basePath": "/",
  "title": "Dani & Javad",
  "dataMode": "sheet-primary",
  "urls": {
    "site": "https://wedding-planning-six.vercel.app/",
    "planning_hub": "https://wedding-planning-six.vercel.app/",
    "resources": "https://wedding-planning-six.vercel.app/resources.html",
    "google_sheet_id": "1OM-zo0rfFiY0KM1G1baqGDpkikHExgEqZTfag3ZvRxw",
    "google_sheet": "https://docs.google.com/spreadsheets/d/1OM-zo0rfFiY0KM1G1baqGDpkikHExgEqZTfag3ZvRxw/edit?usp=sharing",
    "google_sheet_primary": true,
    "google_sheet_label": "Planning Tracker (Google Sheet)",
    "venue_maps": "https://maps.google.com/?q=1361+Fulton+Ave+Suite+103+Sacramento+CA+95825"
  },
  "event": {
    "date": "2026-08-08",
    "time": "1:00 PM \u2013 5:00 PM",
    "rsvp_deadline": "2026-07-11",
    "guests_target": 61,
    "venue": "Unleashed Event Space, 1361 Fulton Ave, Suite 103, Sacramento, CA 95825"
  },
  "hostContact": {
    "name": "Javad Khoshnevisan",
    "phone": "9167648938",
    "day_of_name": "Roni",
    "day_of_phone": "9167648938"
  },
  "faq": [
    {
      "q": "What should I wear?",
      "a": "Black and gold cocktail attire. Please avoid white \u2014 Dani and Javad will be in all white."
    },
    {
      "q": "Are kids welcome?",
      "a": "Yes! We're planning for 11 little ones with kid-friendly food options."
    },
    {
      "q": "What food is served?",
      "a": "La Esperanza tacos with rice and beans \u2014 relaxed afternoon, no formal toasts."
    },
    {
      "q": "Are gifts expected?",
      "a": "Your presence is the gift. Registries are linked on the Resources page if you'd like to contribute."
    },
    {
      "q": "Who do I contact on party day?",
      "a": "Roni, our day-of coordinator: (916) 764-8938"
    }
  ],
  "registries": [
    {
      "name": "Amazon Registry",
      "url": "https://www.amazon.com/wedding/registry",
      "description": "Curated gifts for their new chapter",
      "ready": false,
      "note": "Link updates when registry is live"
    },
    {
      "name": "Honeyfund",
      "url": "https://www.honeyfund.com/",
      "description": "Honeymoon memories fund",
      "ready": false,
      "note": "Personal fund page coming soon"
    },
    {
      "name": "CashApp",
      "url": "https://cash.app/",
      "description": "Quick honeymoon contribution",
      "ready": false,
      "note": "Cashtag shared at the party"
    }
  ],
  "guestTimeline": [
    {
      "time": "1:00 PM",
      "title": "Welcome & Cocktails",
      "desc": "Doors open \u2014 grab a drink and find your seat"
    },
    {
      "time": "1:30 PM",
      "title": "Appetizers Served",
      "desc": "La Esperanza tacos, rice & beans for everyone"
    },
    {
      "time": "2:30 PM",
      "title": "Music & Mingling",
      "desc": "Wonderful music and great company all afternoon"
    },
    {
      "time": "3:30 PM",
      "title": "Photo Moments",
      "desc": "Capture memories with Dani & Javad"
    },
    {
      "time": "4:30 PM",
      "title": "Last Call",
      "desc": "Final toasts and farewell hugs"
    },
    {
      "time": "5:00 PM",
      "title": "Farewell",
      "desc": "Thank you for celebrating with us!"
    }
  ],
  "weather": {
    "summary": "Sacramento in August is warm and sunny \u2014 highs around 93\u00b0F.",
    "tip": "Unleashed Event Space is air-conditioned. Black & gold cocktail attire encouraged."
  },
  "parking": "Street and nearby lot parking on Fulton Ave. Arrive 10 minutes early for easy check-in.",
  "guestDescription": "Join us for a relaxed and joyful afternoon of cocktails, delicious appetizers, wonderful music, and great company as we celebrate Dani & Javad's engagement.",
  "hostChecklist": [
    {
      "id": "final-headcount",
      "text": "Confirm final headcount with venue & caterer",
      "done": false
    },
    {
      "id": "music-playlist",
      "text": "Finalize music playlist",
      "done": false
    },
    {
      "id": "decor-setup",
      "text": "Black & gold decor delivered & staged",
      "done": false
    },
    {
      "id": "rsvp-followup",
      "text": "Follow up with pending RSVPs by July 11",
      "done": false
    },
    {
      "id": "day-of-brief",
      "text": "Brief Roni on run-of-show",
      "done": false
    }
  ]
};
